name: projeto_dart1
description: Projeto da prova pratica 01
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  mailer: ^6.0.1


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.1